language: php

php:
  - 5.5

before_script:
  - composer dumpautoload


script:
  - php -v
  - php -l tests/ServiceContainerTest.php
  - phpunit --bootstrap tests/bootstrap.php tests

notifications:
  email: false
